{% set version = "0.1.2" %}
package:
  name: squeegee
  version: '{{version}}'
source:
  url: 'https://gitlab.com/treangenlab/squeegee/-/archive/v{{ version }}/squeegee-v{{ version }}.tar.gz'
  sha256: 012722b7354a1b0b554ab3b9551c981b402398207b225b4dc20a9a6cb0682d4d 
build:
  noarch: generic
  number: 0
  script: mkdir -p ${PREFIX}/bin && cp squeegee ${PREFIX}/bin && cp -R Squeegee ${PREFIX}/bin
requirements:
  run:
    - python >=3.6
    - kraken
    - samtools
    - bowtie2
    - numpy
    - mash
    - meryl
test:
  imports:
    - Squeegee
  commands:
    - squeegee --help 
about:
  home: https://gitlab.com/treangenlab/squeegee
  license: MIT
  license_file: LICENSE
  summary: squeegee, de novo computational contamination detection tool for metagenomic samples
