{% set version = "0.1.2" %}
package:
  name: squeegee
  version: '{{version}}'
source:
  url: 'https://gitlab.com/treangenlab/squeegee/-/archive/v{{ version }}/squeegee-v{{ version }}.tar.gz'
  sha256: 929c2dd72e24895142ed4761171a0652825997f1be09ce1794b7637718a2f54a 
build:
  noarch: generic
  number: 0
  script: mkdir -p ${PREFIX}/bin && cp squeegee ${PREFIX}/bin && cp -R Squeegee ${PREFIX}/bin
requirements:
  run:
    - python >=3.6
    - kraken
    - samtools
    - bowtie2
    - numpy
    - mash
    - meryl
test:
  imports:
    - Squeegee
about:
  home: https://gitlab.com/treangenlab/squeegee
  license: MIT
  license_file: LICENSE
  summary: squeegee, de novo computational contamination detection tool for metagenomic samples
